api/urls.py
# coding:utf-8                                                                  
                                                                                
from django.conf.urls import url                                                
from django.contrib.auth import views as auth_views                             
                                                                                
from . import views    

app_name = 'api'
urlpatterns = [
    url(r'^kakeibo$', views.kakeibo, name='kakeibo'),
    url(r'^shared$', views.shared, name='shared'),
    url(r'^seisan$', views.seisan, name='seisan'),
    url(r'^kakeibo_month$', views.kakeibo_month, name="kakeibo_month"),
    url(r'^shared_month$', views.shared_month, name="shared_month"),
    url(r'^asset/order$', views.asset_order, name="asset_order"),
    url(r'^asset/status$', views.asset_status, name="asset_status"),
    url(r'^asset/holding$', views.asset_holding, name="asset_holding"),
    url(r'^asset/stock/$', views.asset_stock_all, name="asset_stock_all"),
    url(r'^asset/stock/(?P<code>\w+)$', views.asset_stock, name="asset_stock"),
    url(r'^asset/interactive$', views.asset_slack_interactive, name="asset_slack_interactive"),
    url(r'^asset$', views.asset, name="asset"),
    url(r'^test$', views.test, name="test"),
    url(r'^googlehome/shared$', views.googlehome_shared, name="googlehome_shared"),
]

fmanage/urls.py
from django.conf.urls import url, include
from django.urls import include, path            # includeを追加
from django.contrib import admin
# media
from django.conf import settings
from django.views.static import serve
from django.views.generic import RedirectView
# django-rest-framework
from rest_framework.documentation import include_docs_urls
from rest_framework import routers
from asset.urls import router as asset_router
from kakeibo.urls import router as kakeibo_router
from lancers.urls import router as lancers_router
from web.urls import router as web_router
# accounts
from accounts.views import UserDetailAPIView

router = routers.DefaultRouter()
# router.registry.extend(asset_router.registry)
router.registry.extend(kakeibo_router.registry)
router.registry.extend(lancers_router.registry)
router.registry.extend(web_router.registry)


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='kakeibo/')),
    url(r'^admin/', admin.site.urls),
    url(r'^kakeibo/', include('kakeibo.urls', namespace='kakeibo')),
    url(r'^asset/', include('asset.urls', namespace='asset')),
    url(r'^api/', include('api.urls', namespace='api')),
    path('accounts/', include('allauth.urls')),
    # url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^nams/', include('web.urls', namespace='web')),
    url(r'^document/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('lancers/', include('lancers.urls'), name='lancers'),
    path('auth/', include('djoser.urls.jwt')),
    path('auth/user-detail/', UserDetailAPIView.as_view()),
    url(r'^drm/', include(router.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('docs/', include_docs_urls(title='FK-MANAGEMENT API')))
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

web/urls.py
# coding:utf-8
# from django.conf.urls import url
from django.urls import include, path
from web.views import views_main, views_entry, views_order, views_stock, views_ajax
from web.views import views_api
# django-rest-framework
from rest_framework import routers


app_name = 'web'
urlpatterns = [
    # dashboard
    path('', views_main.Main.as_view(), name='main'),
    path('investment/', views_main.Investment.as_view(), name='investment'),

    # entry
    path('entry/', views_entry.EntryList.as_view(), name='entry_list'),
    path('entry/create/', views_entry.EntryCreate.as_view(), name='entry_create'),
    path('entry/<int:pk>/', views_entry.EntryDetail.as_view(), name='entry_detail'),
    path('entry/<int:pk>/edit/', views_entry.EntryUpdate.as_view(), name='entry_edit'),
    path('entry/<int:pk>/delete/', views_entry.EntryDelete.as_view(), name='entry_delete'),
    # order
    path('order/', views_order.OrderList.as_view(), name="order_list"),
    path('order/create', views_order.OrderCreate.as_view(), name='order_create'),
    path('order/<int:order_id>/', views_order.OrderDetail.as_view(), name='order_detail'),
    path('order/<int:order_id>/edit/', views_order.OrderUpdate.as_view(), name='order_edit'),
    # stock
    path('stock/', views_stock.StockList.as_view(), name="stock_list"),
    path('stock/create/', views_stock.StockCreate.as_view(), name='stock_create'),
    path('stock/<stock_code>/', views_stock.StockDetail.as_view(), name='stock_detail'),
    path('stock/<stock_code>/edit/', views_stock.StockUpdate.as_view(), name='stock_edit'),
    # api
    path('api/create_order/v2/', views_api.CreateOrderAPI.as_view(), name="api_create_order_v2"),
    path('api/create_order/', views_api.create_order, name="api_create_order"),
    path('api/get_current_vals/', views_api.GetCurrentVals.as_view(), name="api_get_current_vals"),
    path('api/receive_alert/', views_api.ReceiveAlert.as_view(), name="api_receive_alert"),
    path('api/slack_interactive/', views_api.SlackInteractive.as_view(), name="api_slack_interactive"),
    # ajax
    path('ajax/get_order/', views_ajax.GetOrder.as_view(), name='ajax_get_order'),
    path('ajax/set_alert/', views_ajax.SetAlert.as_view(), name='ajax_set_alert'),
    path('ajax/buy_order/', views_ajax.BuyOrder.as_view(), name='ajax_buy_order'),
    path('ajax/activate_entry/', views_ajax.ActivateEntry.as_view(), name='ajax_activate_entry'),
    path('ajax/deactivate_entry/', views_ajax.DeactivateEntry.as_view(), name='ajax_deactivate_entry'),
    path('ajax/get_stock_info/', views_ajax.GetStockInfo.as_view(), name='ajax_get_stock_info'),
]

router = routers.DefaultRouter()
router.register('web/stock', views_api.StockViewSet)
router.register('web/order', views_api.OrderViewSet)
router.register('web/entry', views_api.EntryiewSet)
router.register('web/stockvaluedata', views_api.StockValueDataViewSet)
router.register('web/assetstatus', views_api.AssetStatusViewSet)
router.register('web/assettarget', views_api.AssetTargetViewSet)
router.register('web/ipo', views_api.IpoViewSet)
router.register('web/dividend', views_api.DividendViewSet)

web/templates/web/modal/modal_info_sad.html
{% load humanize %}
{% load web_template %}

<button type="button" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#sad_{{sad.id}}">
  <i class="fas fa-external-link-alt"></i>
</button>

<!-- Modal new_stock-->
<div class="modal fade" id="sad_{{sad.id}}" tabindex="-1" role="dialog" aria-labelledby="sad_{{sad.id}}" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <i class="fas fa-info-circle"></i> SAD ({{sad.date}})
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5>HLOCT</h5>
        <table class="table table-responsive-sm">
          <tr>
            <th class="right">H</th>
            <th class="right">L</th>
            <th class="right">O</th>
            <th class="right">C</th>
            <th class="right">T</th>
          </tr>
          <tr>
            <td class="right">{{sad.svd.val_high |yen}}</td>
            <td class="right">{{sad.svd.val_low |yen}}</td>
            <td class="right">{{sad.svd.val_open |yen}}</td>
            <td class="right">{{sad.svd.val_close |yen}}</td>
            <td class="right">{{sad.svd.turnover |intcomma}}</td>
          </tr>
        </table>

        <h5>概要</h5>
        <table class="table table-responsive-sm">
          <tr>
            <th>終値前日比</th>
            <td class="right">{{sad.val_close_dy |yen |safe}}</td>
          </tr>
          <tr>
            <th>終値前日比率</th>
            <td class="right">{{sad.val_close_dy_pct |pct_100 |safe}}</td>
          </tr>
          <tr>
            <th>出来高前日比率</th>
            <td class="right">{{sad.turnover_dy_pct |pct_100 |safe}}</td>
          </tr>
          <tr>
            <th>上ひげ/下ひげ</th>
            <td class="right">{{sad.upper_mustache |intcomma}} / {{sad.lower_mustache |intcomma}}</td>
          </tr>
          <tr>
            <th>線長/割合</th>
            <td class="right">{{sad.val_line |intcomma}} / {{sad.val_line_pct |pct_100}}</td>
          </tr>
        </table>

        <h5>移動平均/トレンド/乖離/乖離率</h5>
        <table class="table table-responsive-sm">
          <tr>
            <th></th>
            <th>移動平均</th>
            <th>トレンド</th>
            <th>乖離</th>
            <th>乖離率</th>
          </tr>
          <tr>
            <th>5日</th>
            <td class="right">{{sad.ma05 |yen}}</td>
            <td>
              {% if sad.is_upper05 %}
              <label class="badge badge-success">
                <i class="fas fa-level-up-alt"></i>
              </label>
              {% else %}
              <label class="badge badge-danger">
                <i class="fas fa-level-down-alt"></i>
              </label>
              {% endif %}
            </td>
            <td class="right">{{sad.ma05_diff |yen |safe}}</td>
            <td class="right">{{sad.ma05_diff_pct |pct_100 |safe}}</td>
          </tr>
          <tr>
            <th>25日</th>
            <td class="right">{{sad.ma25 |yen}}</td>
            <td>
              {% if sad.is_upper25 %}
              <label class="badge badge-success">
                <i class="fas fa-level-up-alt"></i>
              </label>
              {% else %}
              <label class="badge badge-danger">
                <i class="fas fa-level-down-alt"></i>
              </label>
              {% endif %}
            </td>
            <td class="right">{{sad.ma25_diff |yen |safe}}</td>
            <td class="right">{{sad.ma25_diff_pct |pct_100 |safe}}</td>
          </tr>
          <tr>
            <th>75日</th>
            <td class="right">{{sad.ma75 |yen}}</td>
            <td>
              {% if sad.is_upper75 %}
              <label class="badge badge-success">
                <i class="fas fa-level-up-alt"></i>
              </label>
              {% else %}
              <label class="badge badge-danger">
                <i class="fas fa-level-down-alt"></i>
              </label>
              {% endif %}
            </td>
            <td class="right">{{sad.ma75_diff |yen |safe}}</td>
            <td class="right">{{sad.ma75_diff_pct |pct_100 |safe}}</td>
          </tr>
        </table>

        <h5>シグナル</h5>
        <table class="table table-responsive-sm">
          <tr>
            <td>
              {% if sad.val_close_dy_pct >= 0.05 %}終値：前日比5%以上<br>{%endif%}
              {% if sad.val_close_dy_pct <= -0.05 %}終値：前日比5%以下<br>{%endif%}
              {% if sad.turnover_dy_pct >= 1 %}出来高：前日比100%以上<br>{%endif%}
              {%if sad.is_harami%}はらみ線<br>{%endif%}
              {%if sad.is_tsutsumi%}包線<br>{%endif%}
              {%if sad.is_takuri%}たくり線<br>{%endif%}
              {%if sad.is_age_sanpo%}上げ三法<br>{%endif%}
              {%if sad.is_sage_sanpo%}下げ三法<br>{%endif%}
              {%if sad.is_sanku_tatakikomi%}三空叩き込み<br>{%endif%}
              {%if sad.is_sante_daiinsen%}三手大陰線<br>{%endif%}
            </td>
          </tr>
        </table>

      </div>
    </div>
  </div>
</div>

web/templates/web/modal/modal_info_sfds.html
{% load humanize %}
{% load web_template %}

{% if sfds %}
<h5><i class="fas fa-money-check-alt"></i> Stock Financial Data</h5>
<table class="table table-responsive-sm">
  <tr>
    <th></th>
    <th>日付</th>
    <th class="right">営業利益</th>
    <th class="right">売上高</th>
    <th class="right">ROE</th>
    <th class="right">ROA</th>
  </tr>
  {% for sfd in sfds %}
  <tr>
    <td class="right">
      <span data-toggle="modal" data-target="#sfd_{{sfd.id}}"><i class="fas fa-external-link-alt"></i></span>
    </td>
    <td class="right">{{sfd.date}}</td>
    <td class="right" class="right">{{sfd.operating_income |yen |safe}}</td>
    <td class="right" class="right">{{sfd.sales |yen |safe}}</td>
    <td class="right" class="right">{{sfd.roe}}</td>
    <td class="right" class="right">{{sfd.roa}}</td>
  </tr>
  {% endfor %}
</table>

<!-- Modal new_stock-->
{% for sfd in sfds %}
<div class="modal fade" id="sfd_{{sfd.id}}" tabindex="-1" role="dialog" aria-labelledby="sfd_{{sfd.id}}" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_stock_Label">
          <i class="fas fa-info-circle"></i> {{sfd.date}}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-responsive-sm">
          <tr>
            <th>有利子負債</th>
            <td class="right">{{sfd.interest_bearing_debt |yen |safe}}</td>
          </tr>
          <tr>
            <th>ROA</th>
            <td class="right">{{sfd.roa}}</td>
          </tr>
          <tr>
            <th>ROE</th>
            <td class="right">{{sfd.roe}}</td>
          </tr>
          <tr>
            <th>売上高</th>
            <td class="right">{{sfd.sales |yen |safe}}</td>
          </tr>
          <tr>
            <th>総資産</th>
            <td class="right">{{sfd.assets |yen |safe}}</td>
          </tr>
          <tr>
            <th>EPS</th>
            <td class="right">{{sfd.eps}}</td>
          </tr>
          <tr>
            <th>当期利益</th>
            <td class="right">{{sfd.net_income |yen |safe}}</td>
          </tr>
          <tr>
            <th>BPS</th>
            <td class="right">{{sfd.bps}}</td>
          </tr>
          <tr>
            <th>総資産経常利益率</th>
            <td class="right">{{sfd.roa_2}}</td>
          </tr>
          <tr>
            <th>営業利益</th>
            <td class="right">{{sfd.operating_income |yen |safe}}</td>
          </tr>
          <tr>
            <th>自己資本比率</th>
            <td class="right">{{sfd.equity_ratio}}</td>
          </tr>
          <tr>
            <th>資本金</th>
            <td class="right">{{sfd.capital |yen |safe}}</td>
          </tr>
          <tr>
            <th>形状利益</th>
            <td class="right">{{sfd.recurring_profit |yen |safe}}</td>
          </tr>
          <tr>
            <th>自己資本</th>
            <td class="right">{{sfd.equity |yen |safe}}</td>
          </tr>
          <tr>
            <th>PBR</th>
            <td class="right">{{sfd.pbr_f}}</td>
          </tr>
          <tr>
            <th>PER</th>
            <td class="right">{{sfd.per_f}}</td>
          </tr>
          <tr>
            <th>EPS（会社予想）</th>
            <td class="right">{{sfd.eps_f}}</td>
          </tr>
          <tr>
            <th>時価総額</th>
            <td class="right">{{sfd.market_value |yen |safe}}</td>
          </tr>


        </table>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}

web/templates/web/modal/modal_info_stock.html
{% load humanize %}
{% load web_template %}
<!--button-->
<button type="button" class="btn btn-block btn-outline-primary" data-toggle="modal" data-target="#stock_info">
  <i class="fas fa-external-link-alt"></i> Stock Info
</button>

<!-- Modal new_stock-->
<div class="modal fade" id="stock_info" tabindex="-1" role="dialog" aria-labelledby="stock_info" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_stock_Label">
          <i class="fas fa-info-circle"></i> {{entry.stock}}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-responsive-sm">
          <tr>
            <th>市場</th>
          </tr>
          <tr>
            <td>{{entry.stock.market |default:"-"}}</td>
          </tr>
          <tr>
            <th>産業</th>
          </tr>
          <tr>
            <td>{{entry.stock.industry |default:"-"}}</td>
          </tr>
          {% if not entry.stock.is_trust and not entry.stock.industry == 'ETF' %}
          <tr>
            <th>特色</th>
          </tr>
          <tr>
            <td>{{entry.stock.feature}}</td>
          </tr>
          <tr>
            <th>連結事業</th>
          </tr>
          <tr>
            <td>{{entry.stock.consolidated_business}}</td>
          </tr>
          <tr>
            <th>決算</th>
          </tr>
          <tr>
            <td>{{entry.stock.settlement_date}}</td>
          </tr>
          <tr>
            <th>単元株数</th>
          </tr>
          <tr>
            <td>{{entry.stock.unit}}</td>
          </tr>
          <tr>
            <th>配当金</th>
          </tr>
          <tr>
            <td>{{entry.stock.dividend |yen}}</td>
          </tr>
          <tr>
            <th>配当利回り</th>
          </tr>
          <tr>
            <td>{{entry.stock.dividend_yield |pct}}</td>
          </tr>
          <tr>
            <th>最終更新日</th>
          </tr>
          <tr>
            <td>{{entry.stock.updated_at }}</td>
          </tr>
          {% endif %}
        </table>
      </div>
      <div class="modal-footer">

        <a href="{%url 'web:stock_detail' stock_code=entry.stock.code%}" class="btn btn-info">
          Stock Detail <i class="fas fa-arrow-circle-right"></i>
        </a>
      </div>
    </div>
  </div>
</div>

web/templates/web/modal/modal_investment.html
<!--button-->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#investment">
  <i class="fas fa-hand-holding-usd"></i> Investment
</button>
<!--modal-->
<div class="modal fade" id="investment" tabindex="-1" role="dialog" aria-labelledby="investment" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_record_Label">
          <i class="fas fa-hand-holding-usd"></i> Investment
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{%url 'web:investment'%}">
        <div class="modal-body">
          {% csrf_token %}
          <table class="table table-responsive">
            {{investment_form}}
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="post_type" value="investment">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

web/templates/web/modal/modal_new_entry.html
<!-- Modal new-entry -->
<button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#new_entry">
  <i class="fas fa-plus"></i> Create Entry
</button>
<div class="modal fade" id="new_entry" tabindex="-1" role="dialog" aria-labelledby="new_entry" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_entry_Label">
          <i class="fas fa-paw"></i> New Entry
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{%url 'web:entry_create'%}">
        <div class="modal-body">
          {% csrf_token %}
          <table>
            {{ entry_form }}
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="post_type" value="new_entry">Register</button>
        </div>
      </form>
    </div>
  </div>
</div>

web/templates/web/modal/modal_new_order.html
<!--button-->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#order">
  <i class="fas fa-plus-square"></i> New Order
</button>
<!--modal-->
<div class="modal fade" id="order" tabindex="-1" role="dialog" aria-labelledby="order" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_record_Label">
          <i class="fas fa-plus-square"></i> New Order
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{%url 'web:order_create'%}">
        <div class="modal-body">
          {% csrf_token %}
          <table class="table table-responsive">
            {{order_form}}
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="post_type" value="order">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

web/templates/web/modal/modal_new_stock.html
<!--button-->
<button type="button" class="btn btn-block btn-outline-primary" data-toggle="modal" data-target="#new_stock">
  <i class="fas fa-plus"></i> Create Stock
</button>
<!-- Modal new_stock-->
<div class="modal fade" id="new_stock" tabindex="-1" role="dialog" aria-labelledby="new_stock" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_stock_Label">
          <i class="fas fa-plus"></i> New stock
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" id="testajax" action="{%url 'web:stock_create'%}">
        <div class="modal-body">
          {% csrf_token %}
          <input type="hidden" name="post_type" value="stock_form">
          <table class="table table-responsive-sm">
              {{ stock_form }}
            <tr>
              <th>Name:</th>
              <td id="ajax_response_name"></td>
            </tr>
            <tr>
              <th>Market:</th>
              <td id="ajax_response_market"></td>
            </tr>
            <tr>
              <th>Industry:</th>
              <td id="ajax_response_industry"></td>
            </tr>
          </table>
          <p id="ajax_response_msg" style="color: green"></p>
          <p id="ajax_response_msg_error" style="color: red"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            <i class="fas fa-times"></i> Close
          </button>
          <button type="button" class="btn btn-info"    id="stock_ajax"  >
            <i class="fas fa-check"></i> Check
          </button>
          <button type="button" class="btn btn-primary" id="stock_submit">
            <i class="fas fa-plus"></i> Register
          </button>
        </div>
      </form>
    </div>
  </div>
</div>


<!--銘柄名取得-->
<script type="text/javascript">
  $('#stock_ajax').click(function(event){
    var form = $('#testajax');
    console.log($('#testajax [name=post_type]').val())
    console.log(form.serializeArray())

    $.ajax({
      url: "{% url 'web:ajax_get_stock_info' %}",
      method: "GET",
      data: form.serialize(),
      timeout: 10000,
      dataType: "json",
      beforeSend: function(){
        $('#ajax_response_name').text("");
        $('#ajax_response_industry').text("");
        $('#ajax_response_market').text("");
        $('#ajax_response_msg').text("");
        $('#ajax_response_msg_error').text("");
      }
    })
    .done( function(d) {
      if (d.status == true) {
        $('#ajax_response_name').text(d.data.name);
        $('#ajax_response_industry').text(d.data.industry);
        $('#ajax_response_market').text(d.data.market);
        $('#ajax_response_msg').text(d.msg);
        if (d.is_registered == true) {
          $('#ajax_response_msg_error').text(
            "(" + d.data.code + ") " + d.data.name + "は登録済みです"
          );
          $('#stock_submit').prop("disabled", true);
        } else {
          $('#stock_submit').prop("disabled", false);
        }
      } else {
        $('#ajax_response_msg_error').text(d.msg);
      }
    })
    .fail( function(d) {
      $('#ajax_response_msg_error').text("Ajax was failed");
    })
  });
</script>

<!--登録-->
<script type="text/javascript">
  $('#stock_submit').click(function(){
    var form = $('#testajax');
    $('#testajax').submit();
    console.log($('#testajax [name=post_type]').val())
    console.log(form.serialize())
  });
</script>

web/templates/web/modal/modal_sbialert.html
{% load static %}
<!--button-->
<button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#sbialert">
  <i class="far fa-bell"></i> SBI Alert
</button>
<!--modal-->
<div class="modal fade" id="sbialert" tabindex="-1" role="dialog" aria-labelledby="sbialert" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_record_Label">
          <i class="far fa-bell"></i> SBI Alert
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" id="ajax_sbialert">
        <div class="modal-body">
          {% csrf_token %}
          <table class="table table-responsive">
            {{sbialert_form}}
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button id="ajax_sbialert_btn" type="button" class="btn btn-primary" name="post_type" value="sbialert">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>
<style type="text/css">
.hide {
  display: none;
}
.loading {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: rgba(0,0,0,.5);
  background-image: url({% static 'loading.gif' %});
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center center;
  background-size: 150px 150px;
}
</style>
<div class="loading hide"></div>
<script type="text/javascript">
  $('#ajax_sbialert_btn').click(function(event){
    var form = $('#ajax_sbialert');
    $.ajax({
      url: "{% url 'web:ajax_set_alert' %}",
      method: form.prop("method"),
      data: form.serialize(),
      timeout: 10000,
      dataType: "json",
      beforeSend: function(){
				$('.loading').removeClass('hide');
			}
    })
    .done( function(d) {
    	$('.loading').addClass('hide');
      window.alert(d["msg"])
      if (d['status'] == true){location.reload();}
    })
  });
</script>