api/urls.py
# coding:utf-8                                                                  
                                                                                
from django.conf.urls import url                                                
from django.contrib.auth import views as auth_views                             
                                                                                
from . import views    

app_name = 'api'
urlpatterns = [
    url(r'^kakeibo$', views.kakeibo, name='kakeibo'),
    url(r'^shared$', views.shared, name='shared'),
    url(r'^seisan$', views.seisan, name='seisan'),
    url(r'^kakeibo_month$', views.kakeibo_month, name="kakeibo_month"),
    url(r'^shared_month$', views.shared_month, name="shared_month"),
    url(r'^asset/order$', views.asset_order, name="asset_order"),
    url(r'^asset/status$', views.asset_status, name="asset_status"),
    url(r'^asset/holding$', views.asset_holding, name="asset_holding"),
    url(r'^asset/stock/$', views.asset_stock_all, name="asset_stock_all"),
    url(r'^asset/stock/(?P<code>\w+)$', views.asset_stock, name="asset_stock"),
    url(r'^asset/interactive$', views.asset_slack_interactive, name="asset_slack_interactive"),
    url(r'^asset$', views.asset, name="asset"),
    url(r'^test$', views.test, name="test"),
    url(r'^googlehome/shared$', views.googlehome_shared, name="googlehome_shared"),
]

fmanage/urls.py
from django.conf.urls import url, include
from django.urls import include, path            # includeを追加
from django.contrib import admin
# media
from django.conf import settings
from django.views.static import serve
from django.views.generic import RedirectView
# django-rest-framework
from rest_framework.documentation import include_docs_urls
from rest_framework import routers
from asset.urls import router as asset_router
from kakeibo.urls import router as kakeibo_router
from lancers.urls import router as lancers_router
from web.urls import router as web_router
# accounts
from accounts.views import UserDetailAPIView

router = routers.DefaultRouter()
# router.registry.extend(asset_router.registry)
router.registry.extend(kakeibo_router.registry)
router.registry.extend(lancers_router.registry)
router.registry.extend(web_router.registry)


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='kakeibo/')),
    url(r'^admin/', admin.site.urls),
    url(r'^kakeibo/', include('kakeibo.urls', namespace='kakeibo')),
    url(r'^asset/', include('asset.urls', namespace='asset')),
    url(r'^api/', include('api.urls', namespace='api')),
    path('accounts/', include('allauth.urls')),
    # url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^nams/', include('web.urls', namespace='web')),
    url(r'^document/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('lancers/', include('lancers.urls'), name='lancers'),
    path('auth/', include('djoser.urls.jwt')),
    path('auth/user-detail/', UserDetailAPIView.as_view()),
    url(r'^drm/', include(router.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('docs/', include_docs_urls(title='FK-MANAGEMENT API')))
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

kakeibo/urls.py
# coding:utf-8
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required
from kakeibo.views import views_figure, views_list, views_detail, views_create, views_delete
from kakeibo.views import views_main as views
# django-rest-framework
from rest_framework import routers
from kakeibo.views.views_drm import UsagesViewSet, ResourcesViewSet, KakeibosViewSet
from kakeibo.views.views_drm import SharedKakeibosViewSet, CreditItemsViewSet, CreditsViewSet
from kakeibo.views.views_drm import CronKakeiboViewSet, CronSharedViewSet, UsualRecordViewSet
from kakeibo.views.views_drm import EventViewSet


app_name = 'kakeibo'
urlpatterns = [
    # mine
    url(r'^mine/$', views.mine, name='mine'),
    # credit
    url(r'^credit/$', views.credit, name='credit'),
    # shared
    url(r'^shared/$', views.shared, name='shared'),
    # dashboard
    url(r'^$', views.dashboard, name='dashboard'),
    # create
    url(r'^mine/create/$', views_create.KakeiboCreate.as_view(), name="kakeibo_create"),
    url(r'^shared/create/$', views_create.SharedCreate.as_view(), name="shared_create"),
    url(r'^event/create/$', views_create.EventCreate.as_view(), name="event_create"),
    # list
    url(r'^usage/list/$', login_required(views_list.UsageList.as_view()), name="usage_list"),
    url(r'^mine/list/$', login_required(views_list.KakeiboList.as_view()), name="kakeibo_list"),
    url(r'^shared/list/$', views_list.SharedList.as_view(), name="shared_list"),
    url(r'^credit/list/$', login_required(views_list.CreditList.as_view()), name="credit_list"),
    url(r'^credit/items/list/$', login_required(views_list.CreditItemList.as_view()), name="credit_item_list"),
    url(r'^event/list/$', views_list.EventList.as_view(), name="event_list"),
    # detail
    url(r'^usage/detail/(?P<pk>\d+)/$', login_required(views_detail.UsageDetail.as_view()), name="usage_detail"),
    url(r'^mine/detail/(?P<pk>\d+)/$', login_required(views_detail.KakeiboDetail.as_view()), name="kakeibo_detail"),
    url(r'^shared/detail/(?P<pk>\d+)/$', views_detail.SharedDetail.as_view(), name="shared_detail"),
    url(r'^credit/detail/(?P<pk>\d+)/$', login_required(views_detail.CreditDetail.as_view()), name="credit_detail"),
    url(r'^credit/items/detail/(?P<pk>\d+)/$', login_required(views_detail.CreditItemDetail.as_view()), name="credit_item_detail"),
    path('event/detail/<int:pk>/', login_required(views_detail.EventDetail.as_view()), name="event_detail"),
    # update
    url(r'^mine/update/(?P<pk>\d+)/$', login_required(views_detail.KakeiboUpdate.as_view()), name="kakeibo_update"),
    url(r'^shared/update/(?P<pk>\d+)/$', views_detail.SharedUpdate.as_view(), name="shared_update"),
    url(r'^usage/update/(?P<pk>\d+)/$', login_required(views_detail.UsageUpdate.as_view()), name="usage_update"),
    url(r'^credit/update/(?P<pk>\d+)/$', login_required(views_detail.CreditUpdate.as_view()), name="credit_update"),
    url(r'^credit/items/update/(?P<pk>\d+)/$', login_required(views_detail.CreditItemUpdate.as_view()), name="credit_item_update"),
    url(r'^event/update/(?P<pk>\d+)/$', login_required(views_detail.EventUpdate.as_view()), name="event_update"),
    # delete
    path("mine/detail/<int:pk>/delete", views_delete.KakeiboDelete.as_view(), name="kakeibo_delete"),
    path("shared/detail/<int:pk>/delete", views_delete.SharedDelete.as_view(), name="shared_delete"),
    # link_kakeibo_and_credit
    url(r'^link$', views.link_kakeibo_and_credit, name='link_kakeibo_and_credit'),
    # Process
    path("read_csv", views.ReadCSVView.as_view(), name="read_csv"),
    path("usual_record", views.UsualRecordView.as_view(), name="usual_record"),

    # test
    url(r'^test$', views.test, name='test'),

    # figure
    # 資産内訳（今月と先月）
    url(r'^fig/bars_resource$', views_figure.bars_resource, name='bars_resource'),
    # 収支
    url(r'^fig/bars_balance$', views_figure.bars_balance, name='bars_balance'),
    # 月末精算
    url(r'^fig/bars_shared_eom$', views_figure.bars_shared_eom, name='bars_shared_eom'),
    # 円
    url(r'^fig/pie_expense$', views_figure.pie_expense, name='pie_expense'),
    url(r'^fig/pie_resource$', views_figure.pie_resource, name='pie_resource'),
    url(r'^fig/pie_credititem$', views_figure.pie_credititem, name='pie_credititem'),
    url(r'^fig/pie_credit$', views_figure.pie_credit, name='pie_credit'),
    url(r'^fig/pie_shared$', views_figure.pie_shared, name='pie_shared'),
    url(r'^fig/pie_usage_cash$', views_figure.pie_usage_cash, name='pie_usage_cash'),
    url(r'^fig/pie_usage$', views_figure.pie_usage, name='pie_usage'),
    # 棒・線
    url(r'^fig/barline_usage$', views_figure.barline_usage, name='barline_usage'),
    url(r'^fig/barline_expense_cash$', views_figure.barline_expense_cash, name='barline_expense_cash'),
    # 線
    url(r'^fig/lines_usage_cash$', views_figure.lines_usage_cash, name='lines_usage_cash'),
    # test
    url(r'^fig/test$', views_figure.test_figure, name='testfig'),
]

router = routers.DefaultRouter()
router.register(r'kakeibo/usage', UsagesViewSet)
router.register(r'kakeibo/resource', ResourcesViewSet)
router.register(r'kakeibo/kakeibo', KakeibosViewSet)
router.register(r'kakeibo/shared', SharedKakeibosViewSet)
router.register(r'kakeibo/credit', CreditsViewSet)
router.register(r'kakeibo/credititem', CreditItemsViewSet)
router.register(r'kakeibo/cron/kakeibo', CronKakeiboViewSet)
router.register(r'kakeibo/cron/shared', CronSharedViewSet)
router.register(r'kakeibo/usualrecord', UsualRecordViewSet)
router.register(r'kakeibo/event', EventViewSet)

lancers/urls.py
# coding:utf-8
# from django.conf.urls import url
from django.urls import include, path
from lancers.views import Main, OpportunityFormView, SyncToProdView, MentaFormView, MENTAClientAutoComplete
from lancers.views import MENTAClientAutoComplete, CategoryAutoComplete
# django-rest-framework
from rest_framework import routers
from lancers.views import ClientViewSet, CategoryViewSet, OpportunityViewSet, OpportunityWorkViewSet, ServiceViewSet


app_name = 'lancers'
urlpatterns = [
    # dashboard
    path('', Main.as_view(), name='main'),
    path('form/opportunity', OpportunityFormView.as_view(), name='form_opportunity'),
    path('form/menta', MentaFormView.as_view(), name='form_menta'),
    path('sync', SyncToProdView.as_view(), name='sync'),
    path('autocomplete/mentaclient', MENTAClientAutoComplete.as_view(), name='autocomplete-mentaclient'),
    path('autocomplete/category', CategoryAutoComplete.as_view(), name='autocomplete-category'),
]

router = routers.DefaultRouter()
router.register(r'lancers/client', ClientViewSet)
router.register(r'lancers/service', ServiceViewSet)
router.register(r'lancers/category', CategoryViewSet)
router.register(r'lancers/opportunity', OpportunityViewSet)
router.register(r'lancers/opportunitywork', OpportunityWorkViewSet)

web/urls.py
# coding:utf-8
# from django.conf.urls import url
from django.urls import include, path
from web.views import views_main, views_entry, views_order, views_stock, views_ajax
from web.views import views_api
# django-rest-framework
from rest_framework import routers


app_name = 'web'
urlpatterns = [
    # dashboard
    path('', views_main.Main.as_view(), name='main'),
    path('investment/', views_main.Investment.as_view(), name='investment'),

    # entry
    path('entry/', views_entry.EntryList.as_view(), name='entry_list'),
    path('entry/create/', views_entry.EntryCreate.as_view(), name='entry_create'),
    path('entry/<int:pk>/', views_entry.EntryDetail.as_view(), name='entry_detail'),
    path('entry/<int:pk>/edit/', views_entry.EntryUpdate.as_view(), name='entry_edit'),
    path('entry/<int:pk>/delete/', views_entry.EntryDelete.as_view(), name='entry_delete'),
    # order
    path('order/', views_order.OrderList.as_view(), name="order_list"),
    path('order/create', views_order.OrderCreate.as_view(), name='order_create'),
    path('order/<int:order_id>/', views_order.OrderDetail.as_view(), name='order_detail'),
    path('order/<int:order_id>/edit/', views_order.OrderUpdate.as_view(), name='order_edit'),
    # stock
    path('stock/', views_stock.StockList.as_view(), name="stock_list"),
    path('stock/create/', views_stock.StockCreate.as_view(), name='stock_create'),
    path('stock/<stock_code>/', views_stock.StockDetail.as_view(), name='stock_detail'),
    path('stock/<stock_code>/edit/', views_stock.StockUpdate.as_view(), name='stock_edit'),
    # api
    path('api/create_order/v2/', views_api.CreateOrderAPI.as_view(), name="api_create_order_v2"),
    path('api/create_order/', views_api.create_order, name="api_create_order"),
    path('api/get_current_vals/', views_api.GetCurrentVals.as_view(), name="api_get_current_vals"),
    path('api/receive_alert/', views_api.ReceiveAlert.as_view(), name="api_receive_alert"),
    path('api/slack_interactive/', views_api.SlackInteractive.as_view(), name="api_slack_interactive"),
    # ajax
    path('ajax/get_order/', views_ajax.GetOrder.as_view(), name='ajax_get_order'),
    path('ajax/set_alert/', views_ajax.SetAlert.as_view(), name='ajax_set_alert'),
    path('ajax/buy_order/', views_ajax.BuyOrder.as_view(), name='ajax_buy_order'),
    path('ajax/activate_entry/', views_ajax.ActivateEntry.as_view(), name='ajax_activate_entry'),
    path('ajax/deactivate_entry/', views_ajax.DeactivateEntry.as_view(), name='ajax_deactivate_entry'),
    path('ajax/get_stock_info/', views_ajax.GetStockInfo.as_view(), name='ajax_get_stock_info'),
]

router = routers.DefaultRouter()
router.register('web/stock', views_api.StockViewSet)
router.register('web/order', views_api.OrderViewSet)
router.register('web/entry', views_api.EntryiewSet)
router.register('web/stockvaluedata', views_api.StockValueDataViewSet)
router.register('web/assetstatus', views_api.AssetStatusViewSet)
router.register('web/assettarget', views_api.AssetTargetViewSet)
router.register('web/ipo', views_api.IpoViewSet)
router.register('web/dividend', views_api.DividendViewSet)

kakeibo/forms.py
from django import forms
from kakeibo.models import Kakeibos, SharedKakeibos, Credits, CreditItems, Usages, Event
from bootstrap_datepicker_plus import DateTimePickerInput, DatePickerInput
from dal import autocomplete


class KakeiboForm(forms.ModelForm):
    """
    Memo モデルの作成、更新に使われる Django フォーム。
    ModelForm を継承して作れば、HTMLで表示したいフィールドを
    指定するだけで HTML フォームを作ってくれる。
    """
    choices = ((c, c) for c in ["支出（現金）", "支出（クレジット）", "支出（Suica）", "引き落とし", "収入", "振替", "その他"])
    way = forms.TypedChoiceField(choices=choices)
    way.widget.attrs['onchange'] = 'fill_resource()'
    tag_copy_to_shared = forms.BooleanField(required=False, label="共通へコピー")
    usage = forms.ModelChoiceField(
        queryset=Usages.objects.filter(is_active=True).order_by('is_expense', "pk"),
        required=False
    )

    class Meta:
        model = Kakeibos
        fields = [
            'date', 'fee', 'way', 'usage', 'move_from', 'move_to', 'memo', "currency", "rate",
            'event', "tag_copy_to_shared",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        # self.fields['usage'].widget.attrs['class'] = ""
        # self.fields['date'].widget.attrs['readonly'] = 'readonly'


class SharedKakeiboForm(forms.ModelForm):
    """
    Memo モデルの作成、更新に使われる Django フォーム。
    ModelForm を継承して作れば、HTMLで表示したいフィールドを
    指定するだけで HTML フォームを作ってくれる。
    """
    choices_paid_by = ((c, c) for c in ["敬士", "朋子",])
    paid_by = forms.TypedChoiceField(choices=choices_paid_by)
    date = forms.DateField()
    usage = forms.ModelChoiceField(
        queryset=Usages.objects.filter(is_expense=True, is_active=True, is_shared=True),
    )

    class Meta:
        model = SharedKakeibos
        fields = ['date', 'fee', 'usage', 'paid_by', 'memo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['date'].widget.attrs['readonly'] = 'readonly'


class CreditForm(forms.ModelForm):
    """
    Memo モデルの作成、更新に使われる Django フォーム。
    ModelForm を継承して作れば、HTMLで表示したいフィールドを
    指定するだけで HTML フォームを作ってくれる。
    """

    class Meta:
        model = Credits
        fields = ['date', 'debit_date', 'fee', 'credit_item', "memo"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class CreditItemForm(forms.ModelForm):
    """
    Memo モデルの作成、更新に使われる Django フォーム。
    ModelForm を継承して作れば、HTMLで表示したいフィールドを
    指定するだけで HTML フォームを作ってくれる。
    """

    class Meta:
        model = CreditItems
        fields = ['name', 'usage']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UsageForm(forms.ModelForm):
    """
    Memo モデルの作成、更新に使われる Django フォーム。
    ModelForm を継承して作れば、HTMLで表示したいフィールドを
    指定するだけで HTML フォームを作ってくれる。
    """

    class Meta:
        model = Usages
        fields = ['name', 'is_expense', 'memo', 'date', 'is_active', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class EventForm(forms.ModelForm):
    """
    Memo モデルの作成、更新に使われる Django フォーム。
    ModelForm を継承して作れば、HTMLで表示したいフィールドを
    指定するだけで HTML フォームを作ってくれる。
    """

    class Meta:
        model = Event
        fields = ['date', 'name', 'memo', 'detail', 'date', 'sum_plan', 'is_active', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

kakeibo/templates/kakeibo/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'dogP5.gif' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" >
    <!-- Original CSS -->
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/nams.css' %}">
    <!-- Font Awesome Icon -->
    <script src="https://kit.fontawesome.com/0e8797feee.js" crossorigin="anonymous"></script>
<!--    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <!--chart.js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.min.js"></script>
    <!--datepicker-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.20/build/jquery.datetimepicker.full.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.20/jquery.datetimepicker.css">
    <script>
      $( function() {
        let dateFormat = 'yy-mm-dd';
        let datetimeFormat = 'yy-mm-dd ';
        $(".c_date" ).datepicker(
          {
            dateFormat: dateFormat,
          }
        );
        $("#id_date" ).datepicker(
          {
            dateFormat: dateFormat,
          }
        );
        $("#id_date_readcsv" ).datepicker(
          {
            dateFormat: dateFormat,
          }
        );
        $("#id_datetime" ).datetimepicker({
            format:'Y-m-d h:m',
        });
      } );
    </script>
    <!-- D3.js -->
    <script src="https://d3js.org/d3.v4.min.js" type="text/javascript"></script>
    <script src="{% static 'js/techan.js' %}" type="text/javascript"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-info navbar-light navbar-toggleable-sm">
      <a class="navbar-brand" href="{% url 'kakeibo:dashboard' %}">
        <img src="{% static 'dogP5.gif' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        fk-management
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle"></i> Kakeibo
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
              <a class="dropdown-item" href="{% url 'kakeibo:mine' %}">
                <i class="far fa-calendar-plus"></i> Dashboard
              </a>
              <a class="dropdown-item" href="{% url 'kakeibo:kakeibo_list' %}">
                <i class="far fa-list-alt"></i> Record List
              </a>
              <a class="dropdown-item" href="{% url 'kakeibo:usage_list' %}">
                <i class="fas fa-american-sign-language-interpreting"></i> Usage List
              </a>
              <a class="dropdown-item" href="{% url 'kakeibo:link_kakeibo_and_credit' %}">
                <i class="fas fa-link"></i> Link Kakeibo and Credit
              </a>
              <a class="dropdown-item" href="{% url 'kakeibo:event_list' %}">
                <i class="far fa-calendar-check"></i> Event List
              </a>
            </div>
          </li>

          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-people-carry"></i> Shared
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
              <a class="dropdown-item" href="{% url 'kakeibo:shared' %}">
                <i class="far fa-calendar-plus"></i> Dashboard
              </a>
              <a class="dropdown-item" href="{% url 'kakeibo:shared_list' %}">
                <i class="far fa-list-alt"></i> Record List
              </a>
            </div>
          </li>

          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-paw"></i> NAMS
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink3">
              <a class="dropdown-item" href="{% url 'web:main' %}">
                <i class="fas fa-home"></i> NAMS Home
              </a>
              <a class="dropdown-item" href="{% url 'web:entry_list' %}">
                <i class="fas fa-list"></i> Entry
              </a>
              <a class="dropdown-item" href="{% url 'web:stock_list' %}">
                <i class="fas fa-list"></i> Stock
              </a>
              <a class="dropdown-item" href="{% url 'web:order_list' %}">
                <i class="fas fa-list"></i> Order
              </a>
            </div>
          </li>

          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-link"></i> Link
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink4">
              <a class="dropdown-item" href="{% url 'lancers:main' %}">
                <i class="fas fa-laptop-code"></i> Lancers
              </a>
              <a class="dropdown-item" href="/knowledge/">
                <i class="fas fa-book"></i> Knowledge
              </a>
              <a class="dropdown-item" href="/admin/">
                <i class="fas fa-toolbox"></i> Admin
              </a>
              <a class="dropdown-item" href="/drm/">
                <i class="fab fa-python"></i> Django Rest Framework
              </a>
              <a href="{% url 'socialaccount_connections' %}?process=connect" class="dropdown-item">
                <i class="fas fa-user-circle"></i> Social Account
              </a>
            </div>
          </li>
          <li class="nav-item active">
            <a href="/accounts/logout" class="nav-link">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </li>
        </ul>
        <span class="navbar-text">
          <i class="fas fa-user-circle"></i> {{request.user}}
        </span>
      </div>
    </nav>

    {% if messages %}
    {% for msg in messages %}
    <div class="alert alert-{{ msg.tags }} alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>{{ msg.tags }}</strong> {{msg}}
    </div>
    {% endfor %}
    {% endif %}


    {% block body %}{% endblock %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock %}
  </body>
</html>

kakeibo/templates/kakeibo/credititems_form.html
{% extends "kakeibo/base.html" %}
{% load humanize %}
{% block title %}
    Credit-Detail
{% endblock %}

{% block body %}
<div class="container">
    <hr>
    <h1><i class="far fa-credit-card"></i> クレジット項目編集</h1>
    <hr>

    <form method="post">
        <table class="table table-light table-hover table-sm table-bordered table-responsive-md">
            <tr>
                <th>id</th>
                <td>{{object.pk}}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{form.name}}</td>
            </tr>
            <tr>
                <th>Usage</th>
                <td>{{form.usage}}</td>
            </tr>
        </table>
        <div class="row">
            <div class="col-sm-6">
                <button class="btn btn-primary">Save</button>
                <a href="{% url 'kakeibo:credit_item_detail' pk=object.pk%}" class="btn btn-secondary">Back to detail</a>
            </div>
        </div>
        {%csrf_token%}
    </form>
</div>

{% endblock %}