api/urls.py
# coding:utf-8                                                                  
                                                                                
from django.conf.urls import url                                                
from django.contrib.auth import views as auth_views                             
                                                                                
from . import views    

app_name = 'api'
urlpatterns = [
    url(r'^kakeibo$', views.kakeibo, name='kakeibo'),
    url(r'^shared$', views.shared, name='shared'),
    url(r'^seisan$', views.seisan, name='seisan'),
    url(r'^kakeibo_month$', views.kakeibo_month, name="kakeibo_month"),
    url(r'^shared_month$', views.shared_month, name="shared_month"),
    url(r'^asset/order$', views.asset_order, name="asset_order"),
    url(r'^asset/status$', views.asset_status, name="asset_status"),
    url(r'^asset/holding$', views.asset_holding, name="asset_holding"),
    url(r'^asset/stock/$', views.asset_stock_all, name="asset_stock_all"),
    url(r'^asset/stock/(?P<code>\w+)$', views.asset_stock, name="asset_stock"),
    url(r'^asset/interactive$', views.asset_slack_interactive, name="asset_slack_interactive"),
    url(r'^asset$', views.asset, name="asset"),
    url(r'^test$', views.test, name="test"),
    url(r'^googlehome/shared$', views.googlehome_shared, name="googlehome_shared"),
]

fmanage/urls.py
from django.conf.urls import url, include
from django.urls import include, path            # includeを追加
from django.contrib import admin
# media
from django.conf import settings
from django.views.static import serve
from django.views.generic import RedirectView
# django-rest-framework
from rest_framework.documentation import include_docs_urls
from rest_framework import routers
from asset.urls import router as asset_router
from kakeibo.urls import router as kakeibo_router
from lancers.urls import router as lancers_router
from web.urls import router as web_router
# accounts
from accounts.views import UserDetailAPIView

router = routers.DefaultRouter()
# router.registry.extend(asset_router.registry)
router.registry.extend(kakeibo_router.registry)
router.registry.extend(lancers_router.registry)
router.registry.extend(web_router.registry)


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='kakeibo/')),
    url(r'^admin/', admin.site.urls),
    url(r'^kakeibo/', include('kakeibo.urls', namespace='kakeibo')),
    url(r'^asset/', include('asset.urls', namespace='asset')),
    url(r'^api/', include('api.urls', namespace='api')),
    path('accounts/', include('allauth.urls')),
    # url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^nams/', include('web.urls', namespace='web')),
    url(r'^document/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('lancers/', include('lancers.urls'), name='lancers'),
    path('auth/', include('djoser.urls.jwt')),
    path('auth/user-detail/', UserDetailAPIView.as_view()),
    url(r'^drm/', include(router.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('docs/', include_docs_urls(title='FK-MANAGEMENT API')))
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

kakeibo/urls.py
# coding:utf-8
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required
from kakeibo.views import views_figure, views_list, views_detail, views_create, views_delete
from kakeibo.views import views_main as views
# django-rest-framework
from rest_framework import routers
from kakeibo.views.views_drm import UsagesViewSet, ResourcesViewSet, KakeibosViewSet
from kakeibo.views.views_drm import SharedKakeibosViewSet, CreditItemsViewSet, CreditsViewSet
from kakeibo.views.views_drm import CronKakeiboViewSet, CronSharedViewSet, UsualRecordViewSet
from kakeibo.views.views_drm import EventViewSet


app_name = 'kakeibo'
urlpatterns = [
    # mine
    url(r'^mine/$', views.mine, name='mine'),
    # credit
    url(r'^credit/$', views.credit, name='credit'),
    # shared
    url(r'^shared/$', views.shared, name='shared'),
    # dashboard
    url(r'^$', views.dashboard, name='dashboard'),
    # create
    url(r'^mine/create/$', views_create.KakeiboCreate.as_view(), name="kakeibo_create"),
    url(r'^shared/create/$', views_create.SharedCreate.as_view(), name="shared_create"),
    url(r'^event/create/$', views_create.EventCreate.as_view(), name="event_create"),
    # list
    url(r'^usage/list/$', login_required(views_list.UsageList.as_view()), name="usage_list"),
    url(r'^mine/list/$', login_required(views_list.KakeiboList.as_view()), name="kakeibo_list"),
    url(r'^shared/list/$', views_list.SharedList.as_view(), name="shared_list"),
    url(r'^credit/list/$', login_required(views_list.CreditList.as_view()), name="credit_list"),
    url(r'^credit/items/list/$', login_required(views_list.CreditItemList.as_view()), name="credit_item_list"),
    url(r'^event/list/$', views_list.EventList.as_view(), name="event_list"),
    # detail
    url(r'^usage/detail/(?P<pk>\d+)/$', login_required(views_detail.UsageDetail.as_view()), name="usage_detail"),
    url(r'^mine/detail/(?P<pk>\d+)/$', login_required(views_detail.KakeiboDetail.as_view()), name="kakeibo_detail"),
    url(r'^shared/detail/(?P<pk>\d+)/$', views_detail.SharedDetail.as_view(), name="shared_detail"),
    url(r'^credit/detail/(?P<pk>\d+)/$', login_required(views_detail.CreditDetail.as_view()), name="credit_detail"),
    url(r'^credit/items/detail/(?P<pk>\d+)/$', login_required(views_detail.CreditItemDetail.as_view()), name="credit_item_detail"),
    path('event/detail/<int:pk>/', login_required(views_detail.EventDetail.as_view()), name="event_detail"),
    # update
    url(r'^mine/update/(?P<pk>\d+)/$', login_required(views_detail.KakeiboUpdate.as_view()), name="kakeibo_update"),
    url(r'^shared/update/(?P<pk>\d+)/$', views_detail.SharedUpdate.as_view(), name="shared_update"),
    url(r'^usage/update/(?P<pk>\d+)/$', login_required(views_detail.UsageUpdate.as_view()), name="usage_update"),
    url(r'^credit/update/(?P<pk>\d+)/$', login_required(views_detail.CreditUpdate.as_view()), name="credit_update"),
    url(r'^credit/items/update/(?P<pk>\d+)/$', login_required(views_detail.CreditItemUpdate.as_view()), name="credit_item_update"),
    url(r'^event/update/(?P<pk>\d+)/$', login_required(views_detail.EventUpdate.as_view()), name="event_update"),
    # delete
    path("mine/detail/<int:pk>/delete", views_delete.KakeiboDelete.as_view(), name="kakeibo_delete"),
    path("shared/detail/<int:pk>/delete", views_delete.SharedDelete.as_view(), name="shared_delete"),
    # link_kakeibo_and_credit
    url(r'^link$', views.link_kakeibo_and_credit, name='link_kakeibo_and_credit'),
    # Process
    path("read_csv", views.ReadCSVView.as_view(), name="read_csv"),
    path("usual_record", views.UsualRecordView.as_view(), name="usual_record"),

    # test
    url(r'^test$', views.test, name='test'),

    # figure
    # 資産内訳（今月と先月）
    url(r'^fig/bars_resource$', views_figure.bars_resource, name='bars_resource'),
    # 収支
    url(r'^fig/bars_balance$', views_figure.bars_balance, name='bars_balance'),
    # 月末精算
    url(r'^fig/bars_shared_eom$', views_figure.bars_shared_eom, name='bars_shared_eom'),
    # 円
    url(r'^fig/pie_expense$', views_figure.pie_expense, name='pie_expense'),
    url(r'^fig/pie_resource$', views_figure.pie_resource, name='pie_resource'),
    url(r'^fig/pie_credititem$', views_figure.pie_credititem, name='pie_credititem'),
    url(r'^fig/pie_credit$', views_figure.pie_credit, name='pie_credit'),
    url(r'^fig/pie_shared$', views_figure.pie_shared, name='pie_shared'),
    url(r'^fig/pie_usage_cash$', views_figure.pie_usage_cash, name='pie_usage_cash'),
    url(r'^fig/pie_usage$', views_figure.pie_usage, name='pie_usage'),
    # 棒・線
    url(r'^fig/barline_usage$', views_figure.barline_usage, name='barline_usage'),
    url(r'^fig/barline_expense_cash$', views_figure.barline_expense_cash, name='barline_expense_cash'),
    # 線
    url(r'^fig/lines_usage_cash$', views_figure.lines_usage_cash, name='lines_usage_cash'),
    # test
    url(r'^fig/test$', views_figure.test_figure, name='testfig'),
]

router = routers.DefaultRouter()
router.register(r'kakeibo/usage', UsagesViewSet)
router.register(r'kakeibo/resource', ResourcesViewSet)
router.register(r'kakeibo/kakeibo', KakeibosViewSet)
router.register(r'kakeibo/shared', SharedKakeibosViewSet)
router.register(r'kakeibo/credit', CreditsViewSet)
router.register(r'kakeibo/credititem', CreditItemsViewSet)
router.register(r'kakeibo/cron/kakeibo', CronKakeiboViewSet)
router.register(r'kakeibo/cron/shared', CronSharedViewSet)
router.register(r'kakeibo/usualrecord', UsualRecordViewSet)
router.register(r'kakeibo/event', EventViewSet)

kakeibo/views/views_create.py
# coding:utf-8
from django.conf import settings
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse
from django.contrib import messages
from datetime import date
# logging
import logging
logger = logging.getLogger("django")
# model
from kakeibo.models import Kakeibos, SharedKakeibos, Event
from kakeibo.forms import KakeiboForm, SharedKakeiboForm, EventForm
from web.models import AssetStatus


# Create your views here.
# @method_decorator(staff_member_required, name='dispatch')
class KakeiboCreate(LoginRequiredMixin, CreateView):
    model = Kakeibos
    form_class = KakeiboForm
    template_name = "kakeibo/kakeibos_create.html"

    def form_valid(self, form):
        # form.save()
        form.save()
        res = super(KakeiboCreate, self).form_valid(form)
        smsg = "New record was registered"
        # shared
        if form.cleaned_data['tag_copy_to_shared']:
            data = {
                'date': form.cleaned_data['date'],
                'fee': form.cleaned_data['fee'],
                'usage': form.cleaned_data['usage'],
                'paid_by': "敬士",
                'memo': form.cleaned_data['memo'],
            }
            SharedKakeibos.objects.create(**data)
            smsg += " and copied to Shared Kakeibo"
        messages.success(self.request, smsg)
        # 投資口座
        if form.cleaned_data['way'] == "振替" and form.cleaned_data['move_to'].name == "投資口座":
            astatus = AssetStatus.objects.latest('date')
            astatus.buying_power += form.cleaned_data['fee']
            astatus.investment += form.cleaned_data['fee']
            astatus.save()
            messages.info(self.request, "Add ¥{:,} as {}".format(form.cleaned_data['fee'], "Investment"))
        return res

    def get_initial(self, *args, **kwargs):
        initial = super(KakeiboCreate, self).get_initial(**kwargs)
        initial['date'] = date.today()
        initial['event'] = self.request.GET.get('event', None)
        return initial

    def get_success_url(self):
        if self.request.POST.get('source_path', None):
            return self.request.POST['source_path']
        else:
            return reverse('kakeibo:kakeibo_detail', kwargs={'pk': self.object.pk})


class SharedCreate(CreateView):
    model = SharedKakeibos
    form_class = SharedKakeiboForm

    def get_success_url(self):
        return reverse('kakeibo:shared_detail', kwargs={'pk': self.object.pk})


# @method_decorator(staff_member_required, name='dispatch')
class EventCreate(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm

    def form_valid(self, form):
        # form.save()
        form.save()
        res = super(EventCreate, self).form_valid(form)
        smsg = "New Event {} was registered".format(form.cleaned_data['name'])
        messages.success(self.request, smsg)
        return res

    def get_success_url(self):
        if self.request.POST.get('source_path', None):
            return self.request.POST['source_path']
        else:
            return reverse('kakeibo:event_detail', kwargs={'pk': self.object.pk})

kakeibo/views/views_delete.py
# coding:utf-8
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.contrib import messages
# logging
import logging
logger = logging.getLogger("django")
# model
from kakeibo.models import Kakeibos, SharedKakeibos
from kakeibo.forms import KakeiboForm, SharedKakeiboForm


# Create your views here.

class KakeiboDelete(LoginRequiredMixin, DeleteView):
    model = Kakeibos
    form_class = KakeiboForm
    template_name = "kakeibo/kakeibos_delete.html"

    def get_success_url(self):
        return reverse('kakeibo:kakeibo_list')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(self.request, '「{}」を削除しました'.format(self.object))
        return result


class SharedDelete(LoginRequiredMixin, DeleteView):
    model = SharedKakeibos
    form_class = SharedKakeiboForm
    template_name = "kakeibo/sharedkakeibos_delete.html"

    def get_success_url(self):
        return reverse('kakeibo:shared_list')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(self.request, '「{}」を削除しました'.format(self.object))
        return result

kakeibo/views/views_detail.py
# coding:utf-8
from django.conf import settings
from django.views.generic import DetailView, UpdateView
from django.views.generic.list import MultipleObjectMixin
from pure_pagination import PaginationMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse
from django.db.models import Sum, Count, Avg
# logging
import logging
logger = logging.getLogger("django")
# model
from kakeibo.models import Kakeibos, SharedKakeibos, Usages, Resources, Credits, CreditItems, Event
from kakeibo.forms import KakeiboForm, SharedKakeiboForm, CreditForm, CreditItemForm, UsageForm, EventForm


# Create your views here.

# @method_decorator(staff_member_required, name='dispatch')
class KakeiboDetail(LoginRequiredMixin, DetailView):
    model = Kakeibos

    def get_context_data(self, **kwargs):
        res = super().get_context_data(**kwargs)
        return res


class SharedDetail(DetailView):
    model = SharedKakeibos

    def get_context_data(self, **kwargs):
        res = super().get_context_data(**kwargs)
        return res


# @method_decorator(staff_member_required, name='dispatch')
class CreditDetail(LoginRequiredMixin, DetailView):
    model = Credits

    def get_context_data(self, **kwargs):
        res = super().get_context_data(**kwargs)
        return res


# @method_decorator(staff_member_required, name='dispatch')
class CreditItemDetail(LoginRequiredMixin, DetailView):
    model = CreditItems

    def get_context_data(self, **kwargs):
        res = super().get_context_data(**kwargs)
        return res


# @method_decorator(staff_member_required, name='dispatch')
class UsageDetail(LoginRequiredMixin, DetailView):
    model = Usages

    def get_context_data(self, **kwargs):
        res = super().get_context_data(**kwargs)
        return res


# @method_decorator(staff_member_required, name='dispatch')
class EventDetail(PaginationMixin, MultipleObjectMixin, LoginRequiredMixin, DetailView):
    model = Event
    paginate_by = 10

    def get_context_data(self, **kwargs):
        object_list = Kakeibos.objects.filter(event=self.get_object(), is_active=True).order_by('-date')
        context = super(EventDetail, self).get_context_data(object_list=object_list, **kwargs)
        return context


# @method_decorator(staff_member_required, name='dispatch')
class KakeiboUpdate(LoginRequiredMixin, UpdateView):
    model = Kakeibos
    form_class = KakeiboForm

    def get_success_url(self):
        return reverse('kakeibo:kakeibo_detail', kwargs={'pk': self.object.pk})


class SharedUpdate(UpdateView):
    model = SharedKakeibos
    form_class = SharedKakeiboForm

    def get_success_url(self):
        return reverse('kakeibo:shared_detail', kwargs={'pk': self.object.pk})


# @method_decorator(staff_member_required, name='dispatch')
class CreditUpdate(LoginRequiredMixin, UpdateView):
    model = Credits
    form_class =CreditForm

    def get_success_url(self):
        return reverse('kakeibo:credit_detail', kwargs={'pk': self.object.pk})


# @method_decorator(staff_member_required, name='dispatch')
class CreditItemUpdate(LoginRequiredMixin, UpdateView):
    model = CreditItems
    form_class = CreditItemForm

    def get_success_url(self):
        return reverse('kakeibo:credit_item_detail', kwargs={'pk': self.object.pk})


# @method_decorator(staff_member_required, name='dispatch')
class UsageUpdate(LoginRequiredMixin, UpdateView):
    model = Usages
    form_class = UsageForm

    def get_success_url(self):
        return reverse('kakeibo:usage_detail', kwargs={'pk': self.object.pk})


# @method_decorator(staff_member_required, name='dispatch')
class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventForm

    def get_success_url(self):
        return reverse('kakeibo:event_detail', kwargs={'pk': self.object.pk})

kakeibo/templates/kakeibo/modal/modal_new_event.html
<!--============================================================ -->
                          <!--MODAL-->
<!--============================================================ -->
<button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#new_event">
  <i class="far fa-plus-square"></i> New Event
</button>

<!-- Modal new-event -->
<div class="modal fade" id="new_event" tabindex="-1" role="dialog" aria-labelledby="new_event" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_event_Label">
          <i class="far fa-plus-square"></i> New Event
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{% url 'kakeibo:event_create' %}">
        <div class="modal-body">
          {% csrf_token %}
          <table>
            {{ event_form }}
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="post_type" value="new_record">Register</button>
        </div>
        <input type="hidden" name="source_path" value="{{request.get_full_path}}">
      </form>
    </div>
  </div>
</div>

kakeibo/templates/kakeibo/modal/modal_new_record.html
<button type="button" class="btn btn-outline-info btn-block" data-toggle="modal" data-target="#new_record">
  <i class="far fa-plus-square"></i> New Kakeibo
</button>

<!-- Modal new-record -->
<div class="modal fade" id="new_record" tabindex="-1" role="dialog" aria-labelledby="new_record" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_record_Label">
          <i class="fas fa-user-circle"></i> New Kakeibo Record
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{%url 'kakeibo:kakeibo_create' %}">
        <div class="modal-body">
          {% csrf_token %}
          <table>
            {{ kakeibo_form }}
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="post_type" value="new_record">Register</button>
        </div>
        <input type="hidden" name="source_path" value="{{request.get_full_path}}">
      </form>
    </div>
  </div>
</div>

kakeibo/templates/kakeibo/modal/modal_new_record_shared.html
<!-- Modal new-record-shared -->
<div class="modal fade" id="new_record_shared" tabindex="-1" role="dialog" aria-labelledby="new_record" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_record_shared_Label">
          <i class="fas fa-people-carry"></i> New Shared Record
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="">
        <div class="modal-body">
          {% csrf_token %}
          <table>
            {{ shared_form.as_table }}
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="post_type" value="new_record_shared">Register</button>
        </div>
      </form>
    </div>
  </div>
</div>

kakeibo/templates/kakeibo/modal/modal_read_csv.html
<button type="button" class="btn btn-outline-secondary btn-block" data-toggle="modal" data-target="#read_csv">
  <i class="far fa-file-excel"></i> Credit CSV
</button>

<div class="modal fade" id="read_csv" tabindex="-1" role="dialog" aria-labelledby="read_csv" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="read_csv_Label">
          <i class="far fa-file-excel"></i> Read credit CSV
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <script>
        $(function(){
          $('.dropify').dropify();
        })
      </script>
      <form class="form-horizontal" method="post" action="{% url 'kakeibo:read_csv' %}" enctype="multipart/form-data">
        <div class="modal-body">
          <input type="date" name="debit_date" value="" readonly="readonly" id="id_date_readcsv" class="form-control" required="true">
          <input type="file" class="dropify" name="csv">
          {% csrf_token %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="post_type" value="read_csv">Submit</button>
        </div>
        <input type="hidden" name="source_path" value="{{request.get_full_path}}">
      </form>
    </div>
  </div>
</div>

kakeibo/templates/kakeibo/modal/modal_usual_record.html
<button type="button" class="btn btn-outline-success btn-block" data-toggle="modal" data-target="#usual_record">
  <i class="fas fa-clone"></i> Usual_record
</button>

<div class="modal fade" id="usual_record" tabindex="-1" role="dialog" aria-labelledby="usual_record" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new_record_Label">
          <i class="fas fa-clone"></i> Usual Record
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{% url 'kakeibo:usual_record' %}" enctype="multipart/form-data">
        <div class="modal-body">
          {% csrf_token %}
          <input type="hidden" name="post_type" value="usual_record">
          <input type="hidden" name="source_path" value="{{request.get_full_path}}">
          <div class="row">
            {% for ur in usual_records %}
            <div class="col-12 col-md-6">
              <button type="submit" class="btn btn-block btn-outline-success" name="usual_id" value="{{ ur.id }}">
                {% if ur.icon %}{{ ur.icon | safe}}{% endif %} {{ ur.memo }} {{ ur.fee_yen }}
              </button>
            </div>
            {% endfor %}
          </div>
        </div>
      </form>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>