api/urls.py
# coding:utf-8                                                                  
                                                                                
from django.conf.urls import url                                                
from django.contrib.auth import views as auth_views                             
                                                                                
from . import views    

app_name = 'api'
urlpatterns = [
    url(r'^kakeibo$', views.kakeibo, name='kakeibo'),
    url(r'^shared$', views.shared, name='shared'),
    url(r'^seisan$', views.seisan, name='seisan'),
    url(r'^kakeibo_month$', views.kakeibo_month, name="kakeibo_month"),
    url(r'^shared_month$', views.shared_month, name="shared_month"),
    url(r'^asset/order$', views.asset_order, name="asset_order"),
    url(r'^asset/status$', views.asset_status, name="asset_status"),
    url(r'^asset/holding$', views.asset_holding, name="asset_holding"),
    url(r'^asset/stock/$', views.asset_stock_all, name="asset_stock_all"),
    url(r'^asset/stock/(?P<code>\w+)$', views.asset_stock, name="asset_stock"),
    url(r'^asset/interactive$', views.asset_slack_interactive, name="asset_slack_interactive"),
    url(r'^asset$', views.asset, name="asset"),
    url(r'^test$', views.test, name="test"),
    url(r'^googlehome/shared$', views.googlehome_shared, name="googlehome_shared"),
]

fmanage/urls.py
from django.conf.urls import url, include
from django.urls import include, path            # includeを追加
from django.contrib import admin
# media
from django.conf import settings
from django.views.static import serve
from django.views.generic import RedirectView
# django-rest-framework
from rest_framework.documentation import include_docs_urls
from rest_framework import routers
from asset.urls import router as asset_router
from kakeibo.urls import router as kakeibo_router
from lancers.urls import router as lancers_router
from web.urls import router as web_router
# accounts
from accounts.views import UserDetailAPIView

router = routers.DefaultRouter()
# router.registry.extend(asset_router.registry)
router.registry.extend(kakeibo_router.registry)
router.registry.extend(lancers_router.registry)
router.registry.extend(web_router.registry)


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='kakeibo/')),
    url(r'^admin/', admin.site.urls),
    url(r'^kakeibo/', include('kakeibo.urls', namespace='kakeibo')),
    url(r'^asset/', include('asset.urls', namespace='asset')),
    url(r'^api/', include('api.urls', namespace='api')),
    path('accounts/', include('allauth.urls')),
    # url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^nams/', include('web.urls', namespace='web')),
    url(r'^document/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('lancers/', include('lancers.urls'), name='lancers'),
    path('auth/', include('djoser.urls.jwt')),
    path('auth/user-detail/', UserDetailAPIView.as_view()),
    url(r'^drm/', include(router.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('docs/', include_docs_urls(title='FK-MANAGEMENT API')))
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

web/urls.py
# coding:utf-8
# from django.conf.urls import url
from django.urls import include, path
from web.views import views_main, views_entry, views_order, views_stock, views_ajax
from web.views import views_api
# django-rest-framework
from rest_framework import routers


app_name = 'web'
urlpatterns = [
    # dashboard
    path('', views_main.Main.as_view(), name='main'),
    path('investment/', views_main.Investment.as_view(), name='investment'),

    # entry
    path('entry/', views_entry.EntryList.as_view(), name='entry_list'),
    path('entry/create/', views_entry.EntryCreate.as_view(), name='entry_create'),
    path('entry/<int:pk>/', views_entry.EntryDetail.as_view(), name='entry_detail'),
    path('entry/<int:pk>/edit/', views_entry.EntryUpdate.as_view(), name='entry_edit'),
    path('entry/<int:pk>/delete/', views_entry.EntryDelete.as_view(), name='entry_delete'),
    # order
    path('order/', views_order.OrderList.as_view(), name="order_list"),
    path('order/create', views_order.OrderCreate.as_view(), name='order_create'),
    path('order/<int:order_id>/', views_order.OrderDetail.as_view(), name='order_detail'),
    path('order/<int:order_id>/edit/', views_order.OrderUpdate.as_view(), name='order_edit'),
    # stock
    path('stock/', views_stock.StockList.as_view(), name="stock_list"),
    path('stock/create/', views_stock.StockCreate.as_view(), name='stock_create'),
    path('stock/<stock_code>/', views_stock.StockDetail.as_view(), name='stock_detail'),
    path('stock/<stock_code>/edit/', views_stock.StockUpdate.as_view(), name='stock_edit'),
    # api
    path('api/create_order/v2/', views_api.CreateOrderAPI.as_view(), name="api_create_order_v2"),
    path('api/create_order/', views_api.create_order, name="api_create_order"),
    path('api/get_current_vals/', views_api.GetCurrentVals.as_view(), name="api_get_current_vals"),
    path('api/receive_alert/', views_api.ReceiveAlert.as_view(), name="api_receive_alert"),
    path('api/slack_interactive/', views_api.SlackInteractive.as_view(), name="api_slack_interactive"),
    # ajax
    path('ajax/get_order/', views_ajax.GetOrder.as_view(), name='ajax_get_order'),
    path('ajax/set_alert/', views_ajax.SetAlert.as_view(), name='ajax_set_alert'),
    path('ajax/buy_order/', views_ajax.BuyOrder.as_view(), name='ajax_buy_order'),
    path('ajax/activate_entry/', views_ajax.ActivateEntry.as_view(), name='ajax_activate_entry'),
    path('ajax/deactivate_entry/', views_ajax.DeactivateEntry.as_view(), name='ajax_deactivate_entry'),
    path('ajax/get_stock_info/', views_ajax.GetStockInfo.as_view(), name='ajax_get_stock_info'),
]

router = routers.DefaultRouter()
router.register('web/stock', views_api.StockViewSet)
router.register('web/order', views_api.OrderViewSet)
router.register('web/entry', views_api.EntryiewSet)
router.register('web/stockvaluedata', views_api.StockValueDataViewSet)
router.register('web/assetstatus', views_api.AssetStatusViewSet)
router.register('web/assettarget', views_api.AssetTargetViewSet)
router.register('web/ipo', views_api.IpoViewSet)
router.register('web/dividend', views_api.DividendViewSet)

web/models.py
from django.db import models
from datetime import date, datetime
from dateutil.relativedelta import relativedelta
from django.contrib.auth.models import User
from django.db.models import Sum, Avg
from web.functions import mylib_scraping, mylib_analysis
from django.utils import timezone
import logging
logger = logging.getLogger('django')

CHOICES_ENTRY_TYPE = (
    ("短期", "短期"), ("中期", "中期"), ("長期", "長期"),
)


class Stock(models.Model):
    objects = None
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name="更新日時")
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=40)
    is_trust = models.BooleanField("投資信託", default=False)
    market = models.CharField(max_length=30, blank=True, null=True)
    industry = models.CharField(max_length=30, blank=True, null=True)
    fkmanage_id = models.IntegerField(null=True, blank=True, default=None)
    feature = models.CharField(max_length=100, blank=True, null=True, verbose_name="特色")
    consolidated_business = models.CharField(max_length=100, blank=True, null=True, verbose_name="連結事業")
    settlement_date = models.CharField(max_length=10, blank=True, null=True, verbose_name="決算月")
    unit = models.CharField(max_length=10, blank=True, null=True, verbose_name="単元株数")
    dividend = models.IntegerField(blank=True, null=True, verbose_name="配当金")
    dividend_yield = models.FloatField(blank=True, null=True, verbose_name="配当利回り")
    is_listed = models.BooleanField("上場済み", default=True)

    def __str__(self):
        return "({}) {}".format(self.code, self.name)

    def current_val(self):
        data = mylib_scraping.yf_detail(self.code)
        return data['data']['val'] if data['status'] else self.latest_val()

    def latest_val(self):
        svd = StockValueData.objects.filter(stock=self).latest('date')
        return svd.val_close if svd else None

    def latest_val_date(self):
        svd = StockValueData.objects.filter(stock=self).latest('date')
        return svd.date if svd else None

    def analysis(self, days=30):
        print(self)
        target_date = date.today() - relativedelta(days=days)
        svds = StockValueData.objects.filter(stock=self, date__gte=target_date).order_by('date')
        if svds.count() > 1:
            analysis = mylib_analysis.prepare(svds)
            return analysis.iloc[-1]
        else:
            return None

    def save(self, *args, **kwargs):
        # 上場済みであれば、各種情報をスクレイピング
        data = mylib_scraping.yf_detail(self.code)
        if data['status']:
            self.name = data['data']['name']
            self.market = data['data']['market']
            self.industry = data['data']['industry']
            self.is_trust = False if len(str(self.code)) == 4 else True
            if data['data']['industry'] == "REIT":
                dividend = data['data']['financial_data']['予想分配金']
                self.dividend = None if dividend in (None, "---")  else int(float(dividend))
                dividend_yield = data['data']['financial_data']['分配金利回り']
                self.dividend_yield = None if dividend_yield in (None, "---") else dividend_yield
            elif not data['data']['industry'] == "ETF" and not self.is_trust:
                dividend = data['data']['financial_data']['1株配当']
                self.dividend = None if dividend in (None, "---") else int(float(dividend))
                dividend_yield = data['data']['financial_data']['配当利回り']
                self.dividend_yield = None if dividend_yield in (None, "---") else dividend_yield
        profile = mylib_scraping.yf_profile(self.code)
        if profile['status']:
            self.feature = profile['data']["特色"]
            self.consolidated_business = profile['data']["連結事業"]
            self.settlement_date = profile['data']["決算"]
            self.unit = profile['data']["単元株数"]
        return super().save(*args, **kwargs)


class StockValueData(models.Model):
    objects = None
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)
    val_high = models.FloatField()
    val_low = models.FloatField()
    val_open = models.FloatField()
    val_close = models.FloatField()
    turnover = models.FloatField()

    def __str__(self):
        return "{}_{}".format(self.date, self.stock)


class ReasonWinLoss(models.Model):
    objects = None
    reason = models.CharField(max_length=40)
    is_win = models.BooleanField()
    description = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        header = "W" if self.is_win else "L"
        return "{}{}".format(header, self.reason)


class EntryStatus(models.Model):
    objects = None
    status = models.CharField(max_length=20)
    entry_type = models.CharField(
        choices=CHOICES_ENTRY_TYPE, max_length=10, verbose_name="Entry種別",
        null=True, blank=True
    )
    definition = models.CharField(max_length=100)
    min_profit_percent = models.FloatField(help_text="足切り利益率", blank=True, null=True)
    max_holding_period = models.IntegerField(help_text="最大保有期間", blank=True, null=True)
    is_within_week = models.BooleanField(help_text="週跨ぎしないEntry")
    is_within_holding_period = models.BooleanField(default=True, help_text="保有期間超えを許容しない")
    is_for_plan = models.BooleanField(default=False, help_text="Plan向けステータス")

    def __str__(self):
        return self.status


class Entry(models.Model):
    objects = None
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name="更新日時")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="ユーザ")
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, verbose_name="銘柄")
    border_loss_cut = models.FloatField(blank=True, null=True, verbose_name="損切価格")
    border_profit_determination = models.FloatField(blank=True, null=True, verbose_name="利確価格")
    reason_win_loss = models.ForeignKey(ReasonWinLoss, on_delete=models.CASCADE, blank=True, null=True, verbose_name="理由")
    memo = models.TextField(blank=True, null=True, verbose_name="メモ")
    is_plan = models.BooleanField(default=False, verbose_name="EntryPlan", help_text="EntryPlanかどうか")
    is_closed = models.BooleanField(default=False, verbose_name="Closed", help_text="終了したEntryかどうか")
    is_simulated = models.BooleanField(default=False, verbose_name="Simulation", help_text="シミュレーション")
    is_nisa = models.BooleanField(default=False, verbose_name="NISA", help_text="NISA口座")
    num_plan = models.IntegerField(default=0, verbose_name="予定口数")
    val_plan = models.FloatField(blank=True, null=True, verbose_name="予定Entry株価")
    is_in_order = models.BooleanField(default=False, help_text="NAMSから注文中か？", verbose_name="注文中")
    entry_type = models.CharField(choices=CHOICES_ENTRY_TYPE, max_length=10, verbose_name="Entry種別", default="中期")
    status = models.ForeignKey(EntryStatus, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        if self.is_plan:
            head = 'I' if self.is_closed else 'P'
        else:
            head = 'C' if self.is_closed else 'O'
        return "{}{:0>3}_{}".format(head, self.pk, self.stock)

    def val_order(self, is_buy):
        """取引株価"""
        orders = self.order_set.filter(is_buy=is_buy)
        val = 0
        if orders.exists():
            for o in orders:
                val += (o.val * o.num)
            val = val/self.num_order(is_buy)
        return val

    def num_order(self, is_buy):
        """取引口数"""
        orders = self.order_set.filter(is_buy=is_buy)
        num = 0
        if orders.exists():
            num = orders.aggregate(num=Sum('num'))['num']
        return num

    def num_buy(self):
        """買付口数"""
        return self.num_order(is_buy=True)

    def num_sell(self):
        """売付口数"""
        return self.num_order(is_buy=False)

    def val_buy(self):
        """買付株価"""
        return self.val_order(is_buy=True)

    def val_sell(self):
        """売付株価"""
        return self.val_order(is_buy=False)

    def total_buy(self):
        """買付合計"""
        return self.val_buy() * self.num_buy()

    def total_sell(self):
        """売付合計"""
        return self.val_sell() * self.num_sell() if self.num_sell() > 0 else None

    def total_plan(self):
        """Plan合計"""
        return self.val_plan * self.num_plan if self.val_plan else None

    def total_now(self):
        """現在合計"""
        return self.remaining() * self.stock.current_val()

    def num_linked_orders(self):
        """紐づくOrder数"""
        return self.order_set.count()

    def remaining(self):
        """残口数"""
        return self.num_buy() - self.num_sell()

    def profit(self):
        """利益"""
        profit = 0
        for o in self.order_set.all():
            if o.is_buy:
                profit -= (o.num * o.val + o.commission)
            else:
                profit += (o.num * o.val - o.commission)
        if not self.is_closed:
            data = mylib_scraping.yf_detail(self.stock.code)
            if data['status']:
                profit += data['data']['val'] * self.remaining()
        return profit

    def profit_after_tax(self):
        """税引利益"""
        profit = self.profit()
        return round(profit * 0.8) if profit > 0 and not self.is_nisa else profit

    def profit_pct(self):
        """利益率"""
        # return round(self.profit() * 100 / self.val_buy() / self.num_buy(), 1) if self.order_set.exists() else 0
        return self.profit() / self.val_buy() / self.num_buy() if self.order_set.exists() else 0

    def profit_profit_determination(self):
        """利確後の利益額"""
        if self.border_profit_determination:
            num = self.num_plan if self.is_plan else self.num_buy()

web/templates/web/order_detail.html
{% extends "kakeibo/base.html" %}
{% load humanize %}
{% load static %}
{% block title %}
    Order View
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<h4><i class="fas fa-paw"></i> Order Detail</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-sm-6">
			<table class="table table-responsive">
				<tr>
					<th>No</th>
					<td>{{order.id}}</td>
				</tr>
				<tr>
					<th>Stock</th>
					<td>
						<a href="{%url 'web:stock_detail' order.stock.code%}">{{order.stock}}</a>
					</td>
				</tr>
				<tr>
					<th>Datetime</th>
					<td>{{order.datetime}}</td>
				</tr>
				<tr>
					<th>Type</th>
					<td>{% include 'web/part/order_type.html' %}</td>
				</tr>
				<tr>
					<th>Num</th>
					<td>{{order.num |intcomma}}</td>
				</tr>
				<tr>
					<th>Val</th>
					<td>¥{{order.val |intcomma}}</td>
				</tr>
				<tr>
					<th>Commission</th>
					<td>¥{{order.commission |intcomma}}</td>
				</tr>
				<tr>
					<th>Entry</th>
					<td>
						{% if order.entry %}
						<a href="{%url 'web:entry_detail' pk=order.entry.id%}">
							{{order.entry}}
						</a>
						{%else%}-{%endif%}
					</td>
				</tr>
				<tr>
					<th>Chart</th>
					<td>{{order.chart}}</td>
				</tr>
				{% if order.fkmanage_id %}
				<tr>
					<th>fmanage_id</th>
					<td><a href="/admin/asset/orders/{{order.fkmanage_id}}/change/">Link</a></td>
				</tr>
				{% endif %}
			</table>
			<a class="btn btn-outline-info" href="{%url 'web:order_edit' order_id=order.pk%}">
				<i class="fas fa-edit"></i> Edit
			</a>
			<a class="btn btn-outline-secondary" href="{%url 'web:order_list' %}">
				<i class="fas fa-backward"></i> Back
			</a>
		</div>
	</div>
</div>
{% endblock %}

web/templates/web/order_list.html
{% extends "kakeibo/base.html" %}
{% load humanize %}
{% block title %}
    Order List
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<h4><i class="fas fa-paw"></i> Order List</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<table class="table">
				<tr>
					<th>No</th>
					<th>Datetime</th>
					<th>Type</th>
					<th>Stock</th>
					<th>Num</th>
					<th>Val</th>
					<th>Entry</th>
				</tr>
				{% for order in object_list %}
				<tr>
					<td>
						<a href="{%url 'web:order_detail' order_id=order.id%}">
							{{order.pk}}
						</a>
					</td>
					<td>{{order.datetime}}</td>
					<td>{% include 'web/part/order_type.html' %}</td>
					<td>
						<a href="{%url 'web:stock_detail' order.stock.code%}">{{order.stock}}</a>
					</td>
					<td>{{order.num |intcomma}}</td>
					<td>¥{{order.val |intcomma}}</td>
					<td>
						{% if order.entry %}
						<a href="{%url 'web:entry_detail' pk=order.entry.id%}">
							{{order.entry}}
						</a>
						{%else%}-{%endif%}
					</td>
				</tr>
				{% endfor %}
			</table>
			{% include 'web/part/pagination.html' %}
		</div>
	</div>
</div>
{% endblock %}

web/templates/web/stock_detail.html
{% extends "kakeibo/base.html" %}
{% load humanize %}
{% load static %}
{% load web_template %}
{% block title %}
    Stock Detail {{stock}}
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<h4>
				<i class="fas fa-paw"></i> Stock Detail
				{%if stock.is_trust%}
				<label class="badge badge-info">投資信託</label>
				{%else%}
				<label class="badge badge-success">株</label>
				{%endif%}
			</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-sm-6">
			<h5><i class="fas fa-info-circle"></i> Overview</h5>
			<table class="table table-responsive-sm">
				<tr>
					<th>銘柄</th>
					<td>{{stock}}</td>
				</tr>
				<tr>
					<th>市場</th>
					<td>{{stock.market |default:"-"}}</td>
				</tr>
				<tr>
					<th>産業</th>
					<td>{{stock.industry |default:"-"}}</td>
				</tr>
				{% if not stock.is_trust and not stock.industry == 'ETF' %}
				<tr>
					<th>特色</th>
					<td>{{stock.feature}}</td>
				</tr>
				<tr>
					<th>連結事業</th>
					<td>{{stock.consolidated_business}}</td>
				</tr>
				<tr>
					<th>決算</th>
					<td>{{stock.settlement_date}}</td>
				</tr>
				<tr>
					<th>単元株数</th>
					<td>{{stock.unit}}</td>
				</tr>
				<tr>
					<th>配当金</th>
					<td>{{stock.dividend}}</td>
				</tr>
				<tr>
					<th>配当利回り</th>
					<td>{{stock.dividend_yield |pct}}</td>
				</tr>
				{% endif %}
			</table>
			{%include 'web/modal/modal_info_tweet.html' %}
		</div>
		<div class="col-12 col-sm-6">
			<h5><i class="fas fa-tachometer-alt"></i> Current Status</h5>
			<table class="table table-responsive-sm">
				<tr>
					<th>終値⇛現在値</th>
					<th>終値前日比</th>
					<th>出来高前日比</th>
				</tr>
				<tr>
					<td>
						{{svds.last.val_close |yen}} ({{svds.last.date}})
						<br>
						⇛ {%if stock.is_trust%} {{current_val |yen:4}}
						{%else%}{{current_val |yen}}{%endif%}

					</td>
					<td>
						{{sads.first.val_close_dy_pct |pct_100 |safe}}
					</td>
					<td>
						{{sads.first.turnover_dy_pct |pct_100 |safe}}
					</td>
				</tr>
				<tr>
					<th>5日移動平均/乖離率</th>
					<th>25日移動平均/乖離率</th>
					<th>75日移動平均/乖離率</th>
				</tr>
				<tr>
					<td>
						{{sads.first.ma05 |yen}} / {{sads.first.ma05_diff_pct |pct_100 |safe}}
					</td>
					<td>
						{{sads.first.ma25 |yen}} / {{sads.first.ma25_diff_pct |pct_100 |safe}}
					</td>
					<td>
						{{sads.first.ma75 |yen}} / {{sads.first.ma75_diff_pct |pct_100 |safe}}
					</td>
				</tr>
			</table>
			<h5><i class="far fa-list-alt"></i> Entry</h5>
			<table class="table table-responsive-sm">
				<tr>
					<th>No</th>
					<th>Type</th>
					<th>Status</th>
					<th>Open</th>
					<th>Close</th>
					<th>Profit</th>
				</tr>
				{% for entry in stock.entry_set.all %}
				<tr>
					<td>
						<a href="{%url 'web:entry_detail' pk=entry.id %}">
							{{entry.id}}
						</a>
					</td>
					<td>
						{% include 'web/part/entry_type.html' %}
					</td>
					<td>
						{% include 'web/part/entry_close_status.html' %}
					</td>
					<td>{{entry.date_open |date}}</td>
					<td>{{entry.date_close |date}}</td>
					<td class="right">{{entry.profit |yen |safe}}</td>
				</tr>
				{% endfor %}
			</table>

			{% if sbialerts %}
			<h5><i class="far fa-bell"></i> Alert</h5>
			<table class="table table-responsive-sm">
				<tr>
					<th>No</th>
					<th>Open</th>
					<th>Alert</th>
				</tr>
				{% for sbialert in sbialerts %}
				<tr>
					<td>{{sbialert.id}}</td>
					<td>{{sbialert.created_at}}</td>
					<td>{{sbialert.val}} {{sbialert.get_type_display}}</td>
				</tr>
				{% endfor %}
			</table>
			{% endif %}

			{% include 'web/modal/modal_info_sfds.html' %}
		</div>
	</div>

	<div class="row">
		<div class="col-12">
			{% include 'web/modal/modal_sbialert.html' %}
			{% include 'web/modal/modal_new_entry.html' %}
			<a class="btn btn-outline-secondary" href="{%url 'web:stock_list' %}">
				<i class="fas fa-backward"></i> Back to list
			</a>
		</div>
	</div>

	<hr>
	<div class="row">
		<div class="col-12 col-sm-8">
			<h5>
				<i class="fas fa-chart-line"></i> Chart
			</h5>
			<p class="card-title">{{svds.first.date}} ~ {{svds.last.date}}</p>
			<div class="candlestick-1day"></div>
			<p class="card-title">終値</p>
			<canvas id="analysis" width="300" height="150"></canvas>
		</div>

		<div class="col-12 col-sm-4">
			<h5>
				<i class="fas fa-chart-line"></i> Analysis
			</h5>
			{% if sads %}
			{% include 'web/part/trend_type.html' %}
			<table class="table table-responsive">
				<tr>
					<th></th>
					<th>日付</th>
					<th>前日比 (終値/出来高)</th>
					<th>メモ</th>
				</tr>
				{% for sad in sads %}
				{% if sad.is_having_trend %}
				<tr>
					<td>{% include 'web/modal/modal_info_sad.html' %}</td>
					<td>
						<a href="/admin/web/stockanalysisdata/{{sad.id}}/change/">
							{{sad.date |naturalday}}
						</a>
					</td>
					<td>
						{{sad.val_close_dy_pct |pct_100 |safe}}<br>
						{{sad.turnover_dy_pct |pct_100 |safe}}
					</td>
					<td>
						{% if sad.val_close_dy_pct >= 0.05 %}終値：前日比5%以上<br>{%endif%}
						{% if sad.val_close_dy_pct <= -0.05 %}終値：前日比5%以下<br>{%endif%}
						{% if sad.turnover_dy_pct >= 1 %}出来高：前日比100%以上<br>{%endif%}
						{%if sad.is_harami%}はらみ線<br>{%endif%}
						{%if sad.is_tsutsumi%}包線<br>{%endif%}
						{%if sad.is_takuri%}たくり線<br>{%endif%}
						{%if sad.is_age_sanpo%}上げ三法<br>{%endif%}
						{%if sad.is_sage_sanpo%}下げ三法<br>{%endif%}
						{%if sad.is_sanku_tatakikomi%}三空叩き込み<br>{%endif%}
						{%if sad.is_sante_daiinsen%}三手大陰線<br>{%endif%}
					</td>
				</tr>
				{% endif %}
				{% endfor %}
			</table>
			{% endif %}
		</div>
	</div>
</div>
{% include 'web/part/chart.html' %}

<script src="{% static 'js/candlestick.js' %}"></script>
<script>
	window.onload = function() {
		var trades = [
			{% for o in entry.order_set.all %}
			{
				date: "{{o.datetime|date:"Y-m-d"}}",
				type: "{%if o.is_buy%}buy{%else%}sell{%endif%}",
				price: {{o.val}},
				quantity: {{o.num}},
			},
      {% endfor %}
    ];
    var data = [
      {% for svd in svds %}
      {
        Date: "{{svd.date|date:"Y-m-d"}}",
        High: {{svd.val_high}},
        Low: {{svd.val_low}},
        Open: {{svd.val_open}},
        Close: {{svd.val_close}},
        Volume: {{svd.turnover}},
      },
      {% endfor %}
    ];
		displayCandlestick(data, "1day", trades);
		// 画面をリサイズした時に発火する
		$(window).on("resize", function() {
			displayCandlestick(data, "1day", trades);
		});
	}
</script>

{% endblock %}